import Pericia from "~/domain/Pericia";

export default function (): Pericia[] {
  return [
    {
      name: "Acrobacia",
      attr: "AGI",
      penalty: true,
      training: false,
      value: 0,
    },
    {
      name: "Crime",
      attr: "AGI",
      penalty: true,
      training: true,
      value: 0,
    },
    {
      name: "Furtividade",
      attr: "AGI",
      penalty: true,
      training: false,
      value: 0,
    },
    {
      name: "Iniciativa",
      attr: "AGI",
      penalty: false,
      training: false,
      value: 0,
    },
    {
      name: "Pilotagem",
      attr: "AGI",
      penalty: true,
      training: false,
      value: 0,
    },
    {
      name: "Pontaria",
      attr: "AGI",
      penalty: false,
      training: false,
      value: 0,
    },
    {
      name: "Reflexos",
      attr: "AGI",
      penalty: false,
      training: false,
      value: 0,
    },
    {
      name: "Atletismo",
      attr: "FOR",
      penalty: false,
      training: false,
      value: 0,
    },
    {
      name: "Luta",
      attr: "FOR",
      penalty: false,
      training: false,
      value: 0,
    },
    {
      name: "Atualidades",
      attr: "INT",
      penalty: false,
      training: false,
      value: 0,
    },
    {
      name: "Ciências",
      attr: "INT",
      penalty: true,
      training: false,
      value: 0,
    },
    {
      name: "Investigação",
      attr: "INT",
      penalty: false,
      training: false,
      value: 0,
    },
    {
      name: "Medicina",
      attr: "INT",
      penalty: false,
      training: false,
      value: 0,
    },
    {
      name: "Ocultismo",
      attr: "INT",
      penalty: true,
      training: false,
      value: 0,
    },
    {
      name: "Profissão",
      attr: "INT",
      penalty: true,
      training: false,
      value: 0,
    },
    {
      name: "Sobrevivência",
      attr: "INT",
      penalty: false,
      training: false,
      value: 0,
    },
    {
      name: "Tática",
      attr: "INT",
      penalty: true,
      training: false,
      value: 0,
    },
    {
      name: "Tecnologia",
      attr: "INT",
      penalty: true,
      training: false,
      value: 0,
    },
    {
      name: "Adestramento",
      attr: "PRE",
      penalty: true,
      training: false,
      value: 0,
    },
    {
      name: "Artes",
      attr: "PRE",
      penalty: true,
      training: false,
      value: 0,
    },
    {
      name: "Diplomacia",
      attr: "PRE",
      penalty: false,
      training: false,
      value: 0,
    },
    {
      name: "Enganação",
      attr: "PRE",
      penalty: false,
      training: false,
      value: 0,
    },
    {
      name: "Intimidação",
      attr: "PRE",
      penalty: false,
      training: false,
      value: 0,
    },
    {
      name: "Intuição",
      attr: "PRE",
      penalty: false,
      training: false,
      value: 0,
    },
    {
      name: "Percepção",
      attr: "PRE",
      penalty: false,
      training: false,
      value: 0,
    },
    {
      name: "Religião",
      attr: "PRE",
      penalty: true,
      training: false,
      value: 0,
    },
    {
      name: "Vontade",
      attr: "PRE",
      penalty: false,
      training: false,
      value: 0,
    },
    {
      name: "Fortitude",
      attr: "VIG",
      penalty: false,
      training: false,
      value: 0,
    },
  ];
}
